### ISSUE TITLE
STAR runtime

### ISSUE THREAD

**Issue by ctxchris** [lfaino/LoReAn#15]
Hi,

we run lorean with STAR versions 2.6.1 and 2.7.0 and experienced an unbelievably  low mapping speed of 1M PE reads per day.
Manually mapping the same data with the same alignment parameters results in 200M reads per hour.

The main difference I see is in how the index is created. Lorean sets:
`--genomeSAindexNbases 6 
--genomeChrBinNbits 0`
for a 1.5Gbp genome
According to the STAR manual `genomeSAindexNbases` should be set to 
>min(14, log2(GenomeLength)/2 - 1)

which would be 14 in our case.
With `genomeChrBinNbits 0`STAR used almost 700G of RAM, while the recommended value of 15 according to

 >min(18,log2[max(GenomeLength/NumberOfReferences,ReadLength)])

allocated only about 23G.

Best,
Chris

**Comment by lfaino** [comment]
Thanks for the feedback. I will try to calculate these values automatically and make star use them.

I will keep in touch 
Cheers
Luigi

**Comment by lfaino** [comment]
Dear Chris,
I checked in STAR documentation and I have some problem in getting the formula.

formula 1:
i did get the value that you get but what does 14 means in the formula "min(14, log2(GenomeLength)/2 - 1)". do you have any idea?

formula 2:
min(18,log2[max(GenomeLength/NumberOfReferences,ReadLength)])
I assume that the NumberOfReferences is the number of contigs/scaffolds but what about the  ReadLength? do you know which is the value and how to incorporate in the formula?

if you can help, I will change these values in the code and set an automatic way to calculate them?
Otherwise i can write STAR developers.

Cheers

**Comment by lfaino** [comment]
Dear @ctxchris ,
can you test this image:

`docker run -it --rm -v $PWD:/data lfaino/lorean:noiIPRS createUser.py $USER $UID`

in this image, i use a formula to calculate the two values for STAR.
When you run lorean.py, please use the -v option. you will see the command that lorean uses to build the STAR index. please check if the values are correct.
please let me know if it works because i do not have a big genome to test properly the new options.

Cheers
Luigi
