### ISSUE TITLE
CRISPR test data fails

### ISSUE THREAD

**Issue by danwiththeplan** [lfaino/LoReAn#3]
Hi, I have installed LoReAn using Docker as suggested.
```
/usr/bin/docker run -it --rm -v $PWD:/data lfaino/lorean createUser.sh $USER $UID
```
I recompiled GMAP as suggested.
The JR2 example data worked fine.
```
###LOREAN FINISHED WITHOUT ERRORS IN: 0 days 0 hours 48 min 12 sec      ###
```
However the CRISPR example data did not complete:

```
$ lorean.py -a adapter.fasta -rp repeats.scaffold3.bed -sr scaffold3.short_1.fastq,scaffold3.short_2.fastq  -lr scaffold3.long.fasta.gz  -pr scaffold3.prot.fasta -sp crispa scaffold3.fasta -d -f -t 2 --keep_tmp

###STAR MAPPING  STARTED AT:    23:17:38 09-01  ###
        ###BUILD INDEX###
        ###MAP###

###FILTERING OUT LONG READS STARTED AT: 23:17:41 09-01  ###

###TRINITY STARTS AT:   23:17:41 09-01  ###

###GMAP MAPPING  STARTED AT:    23:17:41 09-01  ###
        ###BUILD INDEX###
        ###MAP###

###PASA STARTS AT:      23:18:26 09-01  ###

###BRAKER1 (USING SHORT READS) AND AAT STARTED AT:      23:18:27 09-01  ###
        ###RUNNING BRAKER1 ###
        ###RUNNING AAT ###
        ###CONVERTING AUGUSTUS TO GFF3###
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 522, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 271, in main
    augustus_gff3 = input_evm.convert_augustus(augustus_file, wd)
  File "/opt/LoReAn/code/prepare_evm_inputs.py", line 28, in convert_augustus
    out_f = open(out_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/data/LoReAn_Example/Crispa/LoReAn_annotation/run/braker/crispa/augustus.gff3'
```
Problem appears to be that Augustus fails to produce a `.gff3` file after auto-training? I'm not sure if you can reproduce this error? Thanks for your help here!

**Comment by lfaino** [comment]
I `m testing the tool to see if i can get the error. I write you ASAP

**Comment by lfaino** [comment]
Hi,
can you try to clone the docker image lfaino/lorean:dev by running:

`/usr/bin/docker run -it --rm -v $PWD:/data lfaino/lorean:dev createUser.py $USER $UID`

and re-run:

`lorean.py -a adapter.fasta -rp repeats.scaffold3.bed -sr scaffold3.short_1.fastq,scaffold3.short_2.fastq  -lr scaffold3.long.fasta.gz  -pr scaffold3.prot.fasta -sp crispa scaffold3.fasta -d -f -t 2 --keep_tmp`

let me know if it works
Luigi

**Comment by danwiththeplan** [comment]
Will do, thanks very much..

**Comment by danwiththeplan** [comment]
Same error, although I did not recompile GMAP.

```
$ lorean.py -a adapter.fasta -rp repeats.scaffold3.bed -sr scaffold3.short_1.fastq,scaffold3.short_2.fastq -lr scaffold3.long.fasta.gz -pr scaffold3.prot.fasta -sp crispa scaffold3.fasta -d -f -t 2 --keep_tmp

###STAR MAPPING  STARTED AT:    22:59:24 10-01  ###
        ###BUILD INDEX###
        ###MAP###

###FILTERING OUT LONG READS STARTED AT: 22:59:27 10-01  ###

###TRINITY STARTS AT:   22:59:27 10-01  ###

###GMAP MAPPING  STARTED AT:    22:59:27 10-01  ###
        ###BUILD INDEX###
        ###MAP###

###PASA STARTS AT:      23:00:12 10-01  ###

###BRAKER1 (USING SHORT READS) AND AAT STARTED AT:      23:00:13 10-01  ###
        ###RUNNING BRAKER1 ###
        ###RUNNING AAT ###
        ###CONVERTING AUGUSTUS TO GFF3###
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 522, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 271, in main
    augustus_gff3 = input_evm.convert_augustus(augustus_file, wd)
  File "/opt/LoReAn/code/prepare_evm_inputs.py", line 28, in convert_augustus
    out_f = open(out_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/data/LoReAn_Example/Crispa/LoReAn_annotation/run/braker/crispa/augustus.gff3'
```

**Comment by danwiththeplan** [comment]
Same error if I recompile GMAP.

**Comment by danwiththeplan** [comment]
I also get this error with my own data.. everything works up until then.

**Comment by lfaino** [comment]
Ok.
one think that is strange is the time. It goes very fast. I think that the problem is not in Augustus but in STAR.

I can immagine to problems:
1) did you gunzip the files in the Crispa folder? I add this step in the README file of the crispa example [https://github.com/lfaino/LoReAn_Example/blob/master/README.md]

**Comment by lfaino** [comment]
Ok.
one think that is strange is the time required to arrive to Augustus. With only 2 cores, it should take much longer. It goes very fast. I think that the problem is not in Augustus but in STAR. 

I can imagine 2 problems:

1.	did you gunzip the files in the Crispa folder? The script that you lunch uses FASTQ files but the files that you clone from the repository are FASTQ.GZ. I add the step in the README file for the crispa example [https://github.com/lfaino/LoReAn_Example/blob/master/README.md]. If you did not gunzip, STAR uses file that do not exist and LoReAn goes on without stopping (I will add a check in the future version). 
2.	If this change did not fix the problem, check if the files in the LoReAn_annotation/run/STAR are empty or full. If they are empty, STAR did not work.  You can clone the example repository again and you can use an already mapped BAM file which I pushed. The option is "-sr Crispa.sorted.subsample.bam". If LoReAn works, we have the confirmation that STAR did not work properly and we can investigate further. 
Additionally, GMAP is not able to use .gz files. In the script that you lunch, you have "-lr scaffold3.long.fasta.gz". This is not going to work. You need to gunzip the file and use "-lr scaffold3.long.fasta" 

Let me know if you can fix the problem and thanks for helping.
